services:
  db:
    container_name: fichajespi_db
    image: 'linuxserver/mariadb:10.5.13'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=fichajesroot #Cambiar password si se desea
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=db_fichajespi
      - MYSQL_USER=fichajes #Cambiar usuario si se desea
      - MYSQL_PASSWORD=fichajes #Cambiar password si se desea
    restart: always
    volumes:
      - $HOME/database_data:/config/databases
      - $HOME/database_logs:/config/logs
    networks:
      - db-net

  backendserver:
    container_name: fichajespi_back
    build: ./spring-boot_fichajesPi/
    environment:
      - TZ=Europe/Madrid
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_fichajespi
      - SPRING_DATASOURCE_USERNAME=fichajes #Usar mismo usuario que la base de datos
      - SPRING_DATASOURCE_PASSWORD=fichajes #Usar misma contraseña que la base de datos
      - CLIENT_URL=http://$IP
      - SPRING_MAIL_HOST=smtp.mailtrap.io #poner dominio del servidor smtp
      - SPRING_MAIL_PORT=2525 #poner puerto del servidor smtp
      - SPRING_MAIL_USERNAME=your-user-name #Nombre usuario servidor correos
      - SPRING_MAIL_PASSWORD=your-password #Password servidor correos
      - JWT_SECRET=your-secret-key #Secret key for JWT tokens
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - db-net
      - backend-net

  frontend:
    container_name: fichajespi_front
    build:
      context: ./angular_fichajesPi/
      args:
        - apiURL=http://$IP:8080
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Madrid
    restart: always
    networks:
      - backend-net

  phpmyadmin:
    container_name: fichajespi_dbadmin
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    networks:
      - db-net

  backup:
    image: ghcr.io/aranova/docker-alpine-cron:latest
    restart: unless-stopped
    platform: linux/arm/v7
    environment:
      - 'CRON_STRINGS=5 5 * * * /mysql/backup.sh\n0 5 * * * /aws/deleteOld.sh 20'
      - DB_DUMP_TARGET=s3://bucket/folder #Cambiar
      - DB_USER=root
      - DB_PASS=fichajesroot #Cambiar password si se desea
      - DB_SERVER=db
      - DB_NAMES=db_fichajespi
      - RUN_ONCE=true
      - AWS_ACCESS_KEY_ID=key_id #Cambiar
      - AWS_SECRET_ACCESS_KEY=access_key #Cambiar
      - AWS_DEFAULT_REGION=eu-south-2 #Cambiar
      - AWS_ENDPOINT_URL=https:/s3.eu-south-2.amazonaws.com #Cambiar

      - MYSQLDUMP_OPTS=--skip-ssl
    depends_on:
      - db
    networks:
      - db-net

networks:
  db-net:
  backend-net:
